### ISSUE TITLE
Auth integration

### ISSUE THREAD

**Issue by f0nt4** [hassio-addons/addon-log-viewer#11]
Please integrate with the Auth integration so we don't have to specify a name and password in the config.
As an example you can look at the IDE add-on.

**Comment by noxhirsch** [comment]
👍

**Comment by f0nt4** [comment]
Bot doesn't get we're patiently waiting.

**Comment by f0nt4** [comment]
Maybe this can be achieved by adding ingress support?

**Comment by frenck** [comment]
I’ve tried that, but this thing won’t support Ingress just yet.

**Comment by f0nt4** [comment]
Just yet implies that it might be coming in the future? :)

**Comment by frenck** [comment]
Yep.

**Comment by frenck** [comment]
Authentication & Ingress have been added in v0.5.0

**Comment by f0nt4** [comment]
Awesome. Thanks!
