### ISSUE TITLE
Wont start after upgrading to 0.4.1

### ISSUE THREAD

**Issue by StyxyDog** [hassio-addons/addon-log-viewer#18]
# Problem/Motivation

Upgrading to 0.4.1 and now it fails to start.

## Expected behavior

Older version starts, and is fine if I restore from snapshot.

## Actual behavior

I get this log output...

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

 Hass.io Add-on: Log Viewer
 Browser-based log utility for Hass.io

 Add-on version: 0.4.1
 You are running the latest version of this add-on.
 System: HassOS 2.11  (armv7 / raspberrypi3)
 Home Assistant version: 0.90.2
 Supervisor version: 152
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in e.g, GitHub, forums or the Discord chat.
-----------------------------------------------------------

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[19:47:16] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:47:16] INFO: Starting Log Viewer...
/usr/lib/node_modules/ws-log/node_modules/statuses/index.js:1
(function (exports, require, module, __filename, __dirname) { ������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[19:47:20] INFO: Starting Log Viewer...`

## Steps to reproduce

Not sure, I'm using hass.io on a raspberry pi, I don't think there is anything unusual or special about my install.

## Proposed changes

I can only make it work by downgrading to an old snapshot (version 0.3.1)

**Comment by frenck** [comment]
Please upgrade to 0.5.0

**Comment by StyxyDog** [comment]
Thank you - bug has been resolved following upgrade. :)

**Comment by frenck** [comment]
🎉 
Thank you for letting me know 👍
