### ISSUE TITLE
Log Viewer doesn't connect reliably after transition to Ingress

### ISSUE THREAD

**Issue by rccoleman** [hassio-addons/addon-log-viewer#19]
# Problem/Motivation

After being updated to support Ingress, I'm finding the Log Viewer addon to be not very reliable. 
Sometimes it starts properly and shows a few lines of history as expected, but quite often it just shows a blank page and doesn't update as new log messages come in.  It doesn't seem to matter if it's going through Nabu Casa, through OpenVPN to my house, or on my local wifi network.  There are no errors or interesting log messages in the Home Assistant log, nor anything other than GET requests like the following in the addon logs, even with log-level set to debug:

`[30/Apr/2019:15:07:55 -0700] 200 127.0.0.1, 172.30.32.1(172.30.32.2) GET /js/commands.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36)
`
Overall, it just seems very flaky.  Opening and closing it a few times might eventually get it to work, but most often it doesn't.

## Expected behavior

I expect the log viewer to reliably open, display a few lines of historical logs, and display new log messages in real time.  This was the earlier behavior.

## Actual behavior

I often just get a blank screen and no logs are ever shown.

## Steps to reproduce

Install the addon and start using the default configuration.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by backcountrymountains** [comment]
I also have this issue.

**Comment by rccoleman** [comment]
@frenck I get that there's not much to go on here, but it's very repeatable for me and I don't how to collect more info to try to debug this.  I set the log_level to "trace" and I get this when I'm just getting a blank screen: https://hastebin.com/yuxubasafi.sql

The configuration is default, aside from the log_level:

```
{
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "log_level": "trace"
}
```

I don't know if @backcountrymountains and I are the only ones using this addon or if maybe it's working for everyone else, but I'd love to get to the bottom of this.  I love this addon when it's working.  Any thoughts on how to proceed?

**Comment by sinclairpaul** [comment]
This looks to be a caching issue, specifically on the websocket.js file, if you disable the browser cache (you can do it within the DevTools in Chrome while they are open), does the site load consistently?

**Comment by rccoleman** [comment]
Interesting thought, Paul.  It's working now after disabling the cache, but it also worked immediately before I did that.  I guess that's the same sort of weird, inconsistent behavior that I might see with the cache enabled.  After playing around with it for a while, I'm cautiously optimistic that it's better now.  I'm now getting more historical lines right as I open it up, as I expect and as it used to work.

**Comment by sinclairpaul** [comment]
I can duplicate the issue, it will load the file occasionally, then once cached will throw an invalid http response.  I'm no Javascript expert so not sure what would be causing it, the only thing I could suggest disabling cache-control for that file in the Nginx config of the addon.  At least you have a workaround for now.

**Comment by rccoleman** [comment]
Interesting, I see the websocket.js failure now.  I'll play around with it some more.  Thanks for the pointer.

**Comment by sinclairpaul** [comment]
@frenck I wonder if its just worth serving the public folder from Nginx?, this does seem very similar to some of the challenges around Node-Red (which I believe also uses Express?)

**Comment by sinclairpaul** [comment]
Actually from further testing the cache issue appears to be just masking the issue, if I expose the addon on a port I do not see the issue.  I am thinking there is an issue to do with the Ingress proxy and accessing Websockets without a previous HTTP connection.  For now you could access without cache, or expose the addon on a port and access using that.

**Comment by rccoleman** [comment]
Could be.  I tried using a separate port earlier and while I didn't get the invalid response, it still wasn't behaving as I expected.  When it works properly, it should start by displaying a few historical lines and then start displaying more as they come in real-time.  When I enabled the port, I instead got a blank screen at first and then additional logs started showing in real-time afterward.  Weirdly, I can't reproduce that now, and the behavior is the same between the port (cache or no-cache) and Ingress (no-cache).  I'll keep playing with the port option to see if goes wonky again.

**Comment by nickm324** [comment]
I have the same issue, any progress on this?

**Comment by rccoleman** [comment]
Nope.  Maybe this is something that @dale3h can help with.  I'm having better luck with the dedicated port, but Ingress support is still flaky and behaves as described above when caching is enabled.

**Comment by sinclairpaul** [comment]
For now I would suggest you stay with using the exposed port while the issue is looked at.

**Comment by VelocityMaximus** [comment]
Same issue here. 
Got these as response when loading fails:
hassio.local/:41 GET http://hassio.local:8123/api/hassio_ingress/4SR14BzHHzGabSd6L6JmiRsbusoPYpD2EnD2MQ8hLyk/js/websocket.js net::ERR_INVALID_HTTP_RESPONSE
22:02:02.497 hassio.local/:40 GET http://hassio.local:8123/api/hassio_ingress/4SR14BzHHzGabSd6L6JmiRsbusoPYpD2EnD2MQ8hLyk/js/commands.js net::ERR_INVALID_HTTP_RESPONSE


Few refreshes does the trick sometime.  Disabling cache works.

**Comment by sirs2k** [comment]
> For now I would suggest you stay with using the exposed port while the issue is looked at.

Same issue guys, 
could you shed some light on how we can do any of the 2 temp workarounds?
Thanks

**Comment by rccoleman** [comment]
Go into the configuration for the addon and add a port where it currently says ‘Disabled’. Pick something that’s greater than 1024, and then use a url like this to get to the log viewer:

http://hassio.local:port

Replacing the host and port with the ones that apply to your instance.

**Comment by sirs2k** [comment]
> Go into the configuration for the addon and add a port where it currently says ‘Disabled’. Pick something that’s greater than 1024, and then use a url like this to get to the log viewer:
> 
> http://hassio.local:port
> 
> Replacing the host and port with the ones that apply to your instance.

That worked, thank you very much

**Comment by MickL** [comment]
I do have a fresh hassio install and 90% the logviewer shows nothing. After changing the port it says "502: Bad Gateway"

**Comment by sinclairpaul** [comment]
@rccoleman Could you possibly retest using Ingress with the latest HA releases?

**Comment by rccoleman** [comment]
Sure, I'll keep an eye on it.  It also see that a new release of Log Viewer was just posted today.  Are you aware of any changes that might have helped here?  I haven't seen any acknowledgement from frenck or daleh.

**Comment by sinclairpaul** [comment]
Its changes to Homeassistant itself, not the addon.

**Comment by JMAnguita** [comment]
Tested on 0.95. I'm still having the issue

**Comment by rccoleman** [comment]
Now I'm seeing the same issue again with 0.96.4, complete with invalid HTTP response in the console.  And again, the problem goes away if I disable the cache in the Chrome dev tools.
