### ISSUE TITLE
Feature Request: Syslog forwarding

### ISSUE THREAD

**Issue by macf0x** [hassio-addons/addon-log-viewer#199]
# Problem/Motivation

The syslog capability in HA only provides for notifications. The lack of ability to log events to SEIM or similar platforms, is often sighted as hurdle to using HA in business environments. Creating a separate dedicate addon seems unnecessary and such a feature in this addon would enhance it usefulness.

## Proposed changes

Add options to specify a syslog forwarding address and port, with a toggle enable .

**Comment by frenck** [comment]
That is not really in scope of this add-on.


The sole goal of this add-on was to provide an UI for showing a live log.

../Frenck

**Comment by macf0x** [comment]
That is a shame, given of all the addons, this would be the most appropriate to add this small enhancement.

**Comment by frenck** [comment]
I don't agree, sorry. IMHO, it would add a totally unrelated feature to this add-on.
IMHO such a thing belongs in their own add-on.

**Comment by macf0x** [comment]
I'd go further and suggest it shouldn't be an addon at all.  How it's not a core feature or service in HA in mind-boggling. 
Every discussion on adding such a capability the HA, ends up in hacky workarounds.

**Comment by frenck** [comment]
> How it's not a core feature or service in HA in mind-boggling.

You are now really in the wrong place for the discussion.

../Frenck

**Comment by macf0x** [comment]
FWIW it's just feedback.

**Comment by macf0x** [comment]
Outside of a addon, perhaps you enlighten us looking for such functionality, where they should direct such a FR.

**Comment by frenck** [comment]
Again, your are not in the right place.

**Comment by macf0x** [comment]
And that really isn't an answer. Nvm. Sorry I asked.
