### ISSUE TITLE
please make url "clean"

### ISSUE THREAD

**Issue by 532910** [hassio-addons/addon-log-viewer#204]
# Problem/Motivation

"garbage" in url:
https://ha.tld/a0d7b954_logviewer

## Expected behavior
https://ha.tld/logviewer

The same as terminal:
https://ha.tld/core_ssh

**Comment by frenck** [comment]
Feel free to suggest that to Home Assistant as a feature request. This is not something an add-on can do anything about.

../Frenck

**Comment by 532910** [comment]
so why does the terminal has clean url?

**Comment by 532910** [comment]
https://community.home-assistant.io/t/log-viewer-addon-please-make-url-clean/713393

**Comment by sinclairpaul** [comment]
Just to add some context, the URL isn't "clean", it is prefixed with "core", which as you can see at <https://github.com/home-assistant/supervisor/blob/c3c17b2bc30f24a6940523fad743bf57321705de/supervisor/store/__init__.py#L137> is what is hardcoded in the Supervisor for any HA specific addons.

I'm going to assume that your concern is that the URL may change, which it won't as the hash is based on the repo.

**Comment by 532910** [comment]
Nope, my concern is not that the URL may change, my concern is that the URL is not [clean](https://en.wikipedia.org/wiki/Clean_URL). Moreover, I'm against the fact that some "good" addons like ssh are allowed to have clean url, but "bad" addons are not. I believe all hassio-addons should be considered "good" with a clean url.

**Comment by sinclairpaul** [comment]
So maybe provide a suggestion, i.e. should all community addon's be prefixed with "community", how does that scale exactly.

Either way, the code base for generating the URL's is within the supervisor code, wish you luck with your feature request.
