### ISSUE TITLE
Doesn't start on aarch64 `unprotected error in call to Lua API (bad light userdata pointer)`

### ISSUE THREAD

**Issue by charlietomo** [hassio-addons/addon-log-viewer#21]
# Problem/Motivation

> I can't use this addon as it won't load

## Expected behavior

> Addon loads as normal

## Actual behavior

> Addon stops loading with below error:

`INFO: Starting NGinx...
PANIC: unprotected error in call to Lua API (bad light userdata pointer)`

## Steps to reproduce

> Install addon on new isntall of Hassos on Odroid C2 (aarch64), try and start addon, review logs

## Proposed changes

> I have had the same error before with other addons and they have been fixed by an update; I'm not sure exactly what otherwise I would change it myself

**Comment by frenck** [comment]
This issue has been resolved.
