### ISSUE TITLE
Accessing Log Viewer through Ingress fails and throughs an Invalid HTTP Response

### ISSUE THREAD

**Issue by rccoleman** [hassio-addons/addon-log-viewer#22]
# Problem/Motivation

I'm re-reporting the same issue that is described here https://github.com/hassio-addons/addon-log-viewer/issues/19 because it's happening again with 0.96.5 with exactly the same symptoms.  The only ways to use the log viewer addon reliably are these:

- Disable the cache for the page through the browser dev tools
- Refresh the page and bypass cache every time the page is opened after the first time
- Set up a local port in the addon and get to the log viewer that way

## Expected behavior

I expect the log viewer to open properly and display realtime log content.

## Actual behavior

After opening the log viewer page once (which works), successive attempts to open it result in a blank page and an "invalid HTTP response" in the browser dev console.

## Steps to reproduce

Open the log viewer from the addon page, hit the back arrow or refresh the page.  Sometimes it works, but do it enough and it will eventually stop working.  Sometimes it stops working immediately after the first attempt and sometimes it takes a few tries.

This is what the Chrome dev console shows when I try to refresh the page when the issue is happening:

<img width="545" alt="Screen Shot 2019-08-04 at 7 42 36 AM" src="https://user-images.githubusercontent.com/860888/62425057-ac5d0f00-b68b-11e9-9b7d-04a87c25990f.png">

**Comment by sfedotovs** [comment]
same problem with me.
v 0.99.3 running on hassio.
