### ISSUE TITLE
configuration not located in /config/

### ISSUE THREAD

**Issue by fantapop** [hassio-addons/addon-log-viewer#27]
# Problem/Motivation

Log Viewer is not working for me.  It can't find the log file.

## Expected behavior

Logs are able to be found

## Actual behavior

I've installed hass.io using the method described here: https://github.com/home-assistant/hassio-installer
By default the installer puts the homeassistant configuration in this directory: `/usr/share/hassio/homeassistant`

See lines here: https://github.com/home-assistant/hassio-installer/blob/master/hassio_install.sh#L67-L70

## Steps to reproduce

Install hass.io using hassio-installer
note that configuration is not in /config/

## Proposed changes

I propose adding a configuration parameter that specifies the location of the configuration directory

<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/hassio-installer">home-assistant/hassio-installer</a></strong></div><div>Installer for a generic Linux system. Contribute to home-assistant/hassio-installer development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/hassio-installer">home-assistant/hassio-installer</a></strong></div><div>Installer for a generic Linux system. Contribute to home-assistant/hassio-installer development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
The path you are specifying is on the Host OS. The Hassio ecosystem runs inside Docker. Host paths are mapped inside Docker in the same way, regardless of where you have installed it on the host os.

Simply said, `/config` exists, if not, your Hassio system won't even start at all.

So please provide some error descriptions, reproduction scenario's or logs to work with, because nothing in this report had anything to do with the issue you are experiencing.

**Comment by fantapop** [comment]
Oh, I understand.  Since I'm just setting things up there must have not been a log file yet.  It's there now and I think its working.  I'll close this, thanks for your help!
