### ISSUE TITLE
Running this on a port (for direct non-ingress access) results in SSL error

### ISSUE THREAD

**Issue by timdonovanuk** [hassio-addons/addon-log-viewer#28]
# Problem/Motivation

I want to view logs outside of HA

## Expected behavior

Log viewer on a port

## Actual behavior

Doesn't even start

## Steps to reproduce

Followed the advice here: https://community.home-assistant.io/t/community-hass-io-add-on-log-viewer/64377/25

i.e. " you can enable this again by going into the add-on configuration. A new section show is visible: “Network”. Enter port 4277 (or anything else if you want) in the disabled field. Hit the “SAVE” followed by the “RESTART” button to make your iframe work as before."

The following error happens:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Log Viewer
 Browser-based log utility for Hass.io
-----------------------------------------------------------
 Add-on version: 0.7.0
 You are running the latest version of this add-on.
 System: HassOS 3.8  (amd64 / qemux86-64)
 Home Assistant version: 0.104.3
 Supervisor version: 195
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[22:18:32] FATAL: 
[22:18:32] FATAL: SSL has been enabled using the 'ssl' option,
[22:18:32] FATAL: this requires a SSL certificate file which is
[22:18:32] FATAL: configured using the 'certfile' option in the
[22:18:32] FATAL: add-on configuration.
[22:18:32] FATAL: 
[22:18:32] FATAL: Unfortunately, the file specified in the
[22:18:32] FATAL: 'certfile' option does not exists.
[22:18:32] FATAL: 
[22:18:32] FATAL: Please ensure the certificate file exists and
[22:18:32] FATAL: is placed in the Hass.io '/ssl/' directory.
[22:18:32] FATAL: 
[22:18:32] FATAL: In case you don't have SSL yet, consider getting
[22:18:32] FATAL: a SSL certificate or setting the 'ssl' option
[22:18:32] FATAL: to 'false' in case you are not planning on using
[22:18:32] FATAL: SSL with this add-on.
[22:18:32] FATAL: 
[22:18:32] FATAL: Check the add-on manual for more information.
[22:18:32] FATAL: 
[cont-init.d] nginx.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/allanpersson/200/53963_2.png" width="48" align="right"><div><img src="https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/optimized/3X/f/4/f42b82971fce994297fbc2b269efa248beef897b_2_32x32.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-log-viewer/64377/25">Community Hass.io Add-on: Log Viewer</a></strong></div><div>I love this add-on it makes log viewing so easy.  If i haven’t made a mistake in the setup (which i have checked multiple times) i have a request to make it more easy to toogle between log level.  Right now the setting in logger is overwriting the setting i log viewer, so if i set the level to info in logger and warn in log viewer it shows log level info.  It would be awesome to be able to set the log level in logger to debug, and in log viewer be able to change what the log viewer actually show...</div></blockquote>

**Comment by sinclairpaul** [comment]
The error shown states you have SSL set to true but no certificate specified.
