### ISSUE TITLE
Proposal to improve the appearance

### ISSUE THREAD

**Issue by Robinzona** [hassio-addons/addon-log-viewer#30]
## Proposed changes

I have a suggestion to improve the appearance a bit. 

I played a little with CSS-styles. Displaying log lines without indentation bothered me. I also tried to make the scrollbar look like the look of Hassio itself.

Try adding my lines, I will be glad if they are included in the next release.

.log-line { 
    margin: 0px 5px 1px 5px; }
.log-line:first-child { 
    margin-top: 3px; }
.log .spacer { 
    height: 3px; }

div.log::-webkit-scrollbar { 
    width: 0.8rem; }
div.log::-webkit-scrollbar-thumb { 
    border-radius: 6px; 
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.8); }
div.log::-webkit-scrollbar-track { 
    -webkit-box-shadow: inset 0 0 8px rgb(210, 210, 210); }

**Comment by sinclairpaul** [comment]
I would suggest opening a PR would be the best action for this.

**Comment by Robinzona** [comment]
> I would suggest opening a PR would be the best action for this.

Please tell me right way to do it.
