### ISSUE TITLE
Backup Filesare empty after uploading to Nextcloud

### ISSUE THREAD

**Issue by hruhland** [hassio-addons/addon-log-viewer#31]
# Problem/Motivation

The files copied to Nextcloud can not be used for restoring

## Expected behavior

>Backup is generated in either mode -manual and automated. Then these files are uploaded to my nextcloud

## Actual behavior

> Snapshots are generated and fully OK within home assistent. Files are then copied to Nextcloud, but here they have zero length and content. On HassIO these files are still OK.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
I'm not sure how your issue report is related to this add-on.

**Comment by hruhland** [comment]
Well, aim of this add on is, to automate snapshots and storing them safely on Nextcloud. If the transfer of the snapshot to Nextcloud is corrupted, then this add on does not make sense.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Franck Nijhof <notifications@github.com> Datum: 19.04.20  13:16  (GMT+01:00) An: hassio-addons/addon-log-viewer <addon-log-viewer@noreply.github.com> Cc: hruhland <hruhland@arcor.de>, Author <author@noreply.github.com> Betreff: Re: [hassio-addons/addon-log-viewer] Backup Filesare empty after uploading to Nextcloud (#31) 
I'm not sure how your issue report is related to this add-on.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/hassio-addons/addon-log-viewer/issues/31#issuecomment-616107092",
"url": "https://github.com/hassio-addons/addon-log-viewer/issues/31#issuecomment-616107092",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sinclairpaul** [comment]
> Well, aim of this add on is, to automate snapshots and storing them safely on Nextcloud.

I think you may have the wrong repo, this add on, as per the URL (addon-log-viewer) is for viewing logs....
