### ISSUE TITLE
Side bar icon has been renamed

### ISSUE THREAD

**Issue by Gordontgopher** [hassio-addons/addon-log-viewer#32]
# Problem/Motivation

> Running 0.113b0 an error is logged "Icon mdi:file-document-box-outline was renamed to mdi:text-box-outline"

## Expected behavior

> No issue at the moment, hopefully icon gets renamed before 0.115 :)

## Actual behavior

> No issue at the moment

## Steps to reproduce

> run 0.113b0

## Proposed changes

Icon needs to be renamed in line with update to MDI icons in 0.113.

**Comment by frenck** [comment]
Thanks!

We won't be renaming it until 0.113 is released, as it would cause issues for people not using 0.113 yet (which is currently, at the time of writing, only available as beta).

**Comment by Gordontgopher** [comment]
No problem, was sure you had it in hand, but raised this 'just in case' :)

**Comment by Mariusthvdb** [comment]
release 0.113.1 still has this?

**Comment by frenck** [comment]
@Mariusthvdb Add-on do not depend on add-on releases. So yes, this is still open.

**Comment by Mariusthvdb** [comment]
Ok no worries. Thx

**Comment by si458** [comment]
just attaching to this for peoples info:

`Icon mdi:file-document-box-outline was renamed to mdi:text-box-outline, please change your config, it will be removed in version 0.115`

we have a few months yet as latest is only 0.113.3 👍
