### ISSUE TITLE
Error in "Log Viewer" opening

### ISSUE THREAD

**Issue by liuk4friends** [hassio-addons/addon-log-viewer#35]
# Problem/Motivation

**When I open Log Viewer, I usually encounter this error:**

```
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
    source_header = _init_header(request, token)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 189, in _init_header
    connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
```

**I can see at the top of the Log viewer page (not in logs page)**

## Expected behavior

> (What you expected to happen)

## Actual behavior

**Look above at Problem/Motivation**

## Steps to reproduce

**Open Log Viewer**

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Unfortunately, that is an issue with the Home Assistant Supervisor or Home Assistant Core itself but not something I can handle or fix from the add-on end.

Please report this issue with the Home Assistant project. Thanks 👍
