### ISSUE TITLE
How to filter logs for certain words/domains/entities/etc.? 

### ISSUE THREAD

**Issue by iamkarlson** [hassio-addons/addon-log-viewer#36]
# Problem/Motivation

I need to trace certain logs from a certain logger. 

## Expected behavior

Specify log filtering based on grep(?) expression

## Actual behavior

There's no documentation or setting which would allow me to do that.

## Steps to reproduce

1. Install addon

## Proposed changes

Add documentation, or explicit configuration

**Comment by frenck** [comment]
This add-on just provides access to the log file.
If you want to control what is being logged, please check out the logger integration of Home Assistant.
