### ISSUE TITLE
Repostitory structure for 0.12.0 is not compliant

### ISSUE THREAD

**Issue by snipes040** [hassio-addons/addon-log-viewer#37]
# Problem/Motivation

When I try and add the custom repository it throws an error

## Expected behavior

The repository added

## Actual behavior

Error message of:
Repostitory structure for 0.12.0 is not compliant

## Steps to reproduce

Try to add the custom repository via the HACS menu.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
HACS provides integrations, not add-ons. Add-ons and integrations are not the same things.

**Comment by snipes040** [comment]
Holy crap I haven't had my coffee today! I'm closing this request thank you!

**Comment by frenck** [comment]
Hehehe in that case: Good morning 🌞  Enjoy your coffee ☕ and Happy Holidays 🎄
