### ISSUE TITLE
Syslog export

### ISSUE THREAD

**Issue by mzac** [hassio-addons/addon-log-viewer#6]
# Problem/Motivation

It would be interesting if this addon could also have a configuration section for sending lots out to an external syslog server.  Different types of syslog servers exists so tcp/udp and port numbers would have to be settable.  Maybe just using 'nc' to stream them out when tailing the logs?

## Expected behavior

Be able to see homeassistant logs on a remote syslog server

## Actual behavior

Homeassitant logs are only on the homeassitant server

## Steps to reproduce

n/a

## Proposed changes

See above in motivation section

**Comment by dale3h** [comment]
I had a quick look to see if there are any existing npm syslog client modules, and sure enough, there is one that implements both the [BSD Syslog Protocol RFC 3164][rfc3164] and the [Syslog Protocol RFC 5424][rfc5424].

I will try to look into implementing this feature in the near future.

[rfc3164]: https://www.ietf.org/rfc/rfc3164.txt
[rfc5424]: https://tools.ietf.org/html/rfc5424

**Comment by mzac** [comment]
Awesome!  Do you think it's also possible to monitor the logs of all other containers and push those out via syslog as well?
