### ISSUE TITLE
Revise/improve all log messages

### ISSUE THREAD

**Issue by frenck** [hassio-addons/addon-log-viewer#7]
# Problem/Motivation

There are several reasons for this:

- Not all log messages are consistent across all add-ons.
- Some messages are unclear to the novice user.

**Comment by dale3h** [comment]
@frenck Was this issue opened as part of a project to improve log messages across all addons, or is it specific to the log viewer addon?

**Comment by frenck** [comment]
all, and the current idea is to include a large part of it into bashio. For now, I'm kinda trying to get a better image on upcoming Hass.io changes to see/learn what is actually needed.
